apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  namespace: php-app
  labels:
    app: php-app
data:
  APP_NAME: "PHP-Azure-DevOps-AKS"
  APP_ENV: "production"
  ENVIRONMENT: "AKS"
  SERVER_TYPE: "Apache-PHP"
  DEPLOYMENT_PLATFORM: "Azure Kubernetes Service"